version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Frontend port
      - "8001:8001"  # Backend port
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - db
    restart: unless-stopped
    # Enable watching for file changes
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.web
    # Override the CMD to include development mode features
    command: >
      sh -c "
        if [ -d alembic ]; then
          reflex db migrate
        fi &&
        reflex run --env prod
      "

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-genomicvalley}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data: