services:
  web:
    image: vishal1908/genomicvalley:latest   
    ports:
      - "3001:3001"  
      - "8001:8001"  
    environment:
      - DATABASE_URL=${team.DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - db
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.web
    command: >
      sh -c "
        if [ -d alembic ]; then
          reflex db migrate
        fi &&
        reflex run --env prod
      "

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${team.POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${team.POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${team.POSTGRES_DB:-genomicvalley}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data: