from .pages import (
    index,
    contact_page,
    about_us,
    diagnostic_services,
    research_services,
    page_not_found,
    news_and_updates,
    admin_login,
    dashboard,
    logout,
    contact_dashboard,
    career_page,
    create_announcement_page,
)

__all__ = [
    "index",
    "contact_page",
    "about_us",
    "diagnostic_services",
    "research_services",
    "page_not_found",
    "news_and_updates",
    "admin_login",
    "dashboard",
    "logout",
    "contact_dashboard",
    "career_page",
    "create_announcement_page",
]
